site_name: Irezia - Wiki
repo_name: Irezia-Wiki on GitHub
edit_uri: edit/main/docs/
repo_url: https://github.com/superhize/irezia-wiki
copyright: '© 2021  Irezia'
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  language: fr
  logo: img/logo.png
  favicon: img/logo.png
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - search.share
    - search.suggest
  palette:
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true
  - pymdownx.critic:
      mode: view
  - pymdownx.keys
  - pymdownx.progressbar
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.smartsymbols
plugins:
  - git-revision-date-localized
  - search
  - tooltips
nav:
  - 'Home':
    - 'Bienvenue': index.md
    - 'Aperçu':
        - 'Quêtes': quete.md
        - 'Jobs': jobs.md
        - 'Skills': skills.md
        - 'Collections': collections.md
        - 'Donjons': donjons.md
        - 'Events': events.md
    - 'Contribuer': contribuer.md
  - 'Jobs':
      Mineur: Jobs/Mineur.md
      Agriculteur: Jobs/Agriculteur.md
      Bûcheron: Jobs/Bucheron.md
      Pêcheur: Jobs/Pecheur.md
      Chasseur: Jobs/Chasseur.md
  - 'Skills':
      Mining: Skills/Mineur.md
      Farming: Skills/Farming.md
      Combat: Skills/Combat.md
      Foraging: Skills/Foraging.md
      Enchanting: Skills/Enchanting.md
      Alchemy: Skills/Alchemy.md
      Fishing: Skills/Fishing.md
  - 'Quêtes':
      Introduction: Quetes/Introduction.md
  - 'Enchantements': enchant.md

