site_name: Irezia - Wiki
repo_name: Irezia-Wiki on GitHub
edit_uri: edit/main/docs/src/markdown
repo_url: https://github.com/superhize/irezia-wiki
copyright: "© 2022  Irezia"
docs_dir: docs/src/markdown
theme:
  name: material
  custom_dir: docs/theme
  icon:
    logo: material/book-open-page-variant
  palette:
    scheme: dracula
    primary: deep purple
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - search.share
    - navigation.indexes
    - search.suggest
nav:
  - "Accueil":
      - "Bienvenue": "index.md"
      - "Systèmes principaux":
          - "Quêtes": quete.md
          - "Skills": skills.md
          - "Collections": collections.md
          - "Enchantements": enchant.md
          - "Métiers": jobs.md
      - "Systèmes secondaires":
          - "Audio": audio.md
          - "Artéfacts": artefact.md
          - "Advanced Achievement": aach.md
          - "TimedQuestion": timedquestion.md
      - "Cartes":
          - "Villes": villes.md
          - "Map ressources": ressources.md
      - "Commerce":
          - "Hôtel de ventes": hdv.md
          - "Banque": banque.md
      - "Site":
          - "Vote": vote.md
          - "Boutique": boutique.md
          - "Contribuer au Wiki": contribuer.md
      - "Minecraft":
          - "Optimiser Minecraft": optimiser.md
      - "Serveur":
          - "Avertissement de durabilité": serveur/durability.md
  - "Systèmes principaux":
      - "Quêtes": quete.md
      - "Skills": skills.md
      - "Collections": collections.md
      - "Enchantements": enchant.md
      - "Métiers": jobs.md
  - "Systèmes secondaires":
      - "Audio": audio.md
      - "Artéfacts": artefact.md
      - "Advanced Achievement": aach.md
      - "TimedQuestion": timedquestion.md
  - "Cartes":
      - "Villes": villes.md
      - "Map ressources": ressources.md
  - "Commerce":
      - "Hôtel de ventes": hdv.md
      - "Banque": banque.md
  - "Site":
      - "Vote": vote.md
      - "Boutique": boutique.md
      - "Contribuer au Wiki": contribuer.md
  - "Minecraft":
      - "Optimiser Minecraft": optimiser.md
  - "Serveur":
      - "Avertissement de durabilité": serveur/durability.md

markdown_extensions:
  - def_list
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
      permalink: true
  - admonition
  - pymdownx.smartsymbols
  - pymdownx.betterem
  - attr_list
  - tables
  - abbr
  - footnotes
  - md_in_html
  - pymdownx.highlight
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar
  - pymdownx.arithmatex:
      generic: true
      block_tag: "pre"
  - pymdownx.mark
  - pymdownx.striphtml:
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.saneheaders

extra:
  disqus: irezia
  analytics:
    provider: google
    property: G-ZWHE15VHDT
extra_css:
  - assets/pymdownx-extras/extra.css
  - assets/css/extra.css?v=4
extra_javascript:
  - assets/pymdownx-extras/extra-loader.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  # - assets/js//tablesort.js
plugins:
  - search
  - git-revision-date-localized
