name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1.8.5
        if: always()
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material==8.0.0b2
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-tooltips
      - run: mkdocs gh-deploy --force
